### ISSUE TITLE
Provide convenience aliases for put, delete

### ISSUE THREAD

**Issue by wilzbach** [ikod/dlang-requests#34]
Hey there,

It's great to see your nice library improving over time :)
When interacting with REST APIs using `PUT` and `DELETE` is quite common.

Would you accept a PR that adds convenience alias:

1) to `Request`, e.g. `alias put = exec!"PUT"`, ...
2) globally e.g. `putContent`, `deleteContent`

**Comment by ikod** [comment]
Hello,
Thanks for your interest.
Re. PR - sure. If it will not break unittests (also would be nice to add unittests for new features) - why not?

I'd also like to make some cleanup in API - it seems that some interfaces overlaps - for example there are several ways to use query parameters (using string dictionary and using QueryParams). May be this will be my next goal, but I'm afraid to break others code.

**Comment by wilzbach** [comment]
So when I add the following to `requests.d`:

```d
template exec(string method="GET") {
    Response exec(A...)(A args) {
        return _http.exec!(method)(args);
    }
}
alias put = exec!"PUT";
```

then I get this weird error from `Tuple.opAssign`:

```d
requests 0.4.0+commit.4.g520d041: building configuration "__test__std__"...
/usr/include/dlang/dmd/std/typecons.d(740,39): Error: template std.algorithm.mutation.swap cannot deduce function from argument types !(Tuple!(_Response delegate(const(App), ref HTTPD_Request, RequestArgs), RequestArgs))(Tuple!(_Response delegate(const(App), ref HTTPD_Request, RequestArgs), "handler", RequestArgs, "args"), Tuple!(_Response delegate(const(App), ref HTTPD_Request, RequestArgs), "handler", RequestArgs, "args")), candidates are:
/usr/include/dlang/dmd/std/algorithm/mutation.d(2359,6):        std.algorithm.mutation.swap(T)(ref T lhs, ref T rhs) if (isBlitAssignable!T && !is(typeof(lhs.proxySwap(rhs))))
/usr/include/dlang/dmd/std/algorithm/mutation.d(2575,6):        std.algorithm.mutation.swap(T)(ref T lhs, ref T rhs) if (is(typeof(lhs.proxySwap(rhs))))
```

So it seems that a trivial `alias` doesn't work that well.
Interestingly it compiles fine with ldc 1.0.0 (2.070). So this could be a regression.

> I'd also like to make some cleanup in API - it seems that some interfaces overlaps - for example there are several ways to use query parameters (using string dictionary and using QueryParams). May be this will be my next goal, but I'm afraid to break others code.

As long as you provide a nice changelog and use [semantic versioning](http://semver.org/) you shouldn't worry too much about breaking code. Thanks to DUB and semantic versioning you won't break existing code. Only motivated users who want to play with the newest and hottest will be affected ;-)

**Comment by ikod** [comment]
Hello!
Do you use 2.073? It doesn't work for me, I received the same error. I
placed issue to dmd ticket system and rolled back to 2.072.2

6 Фев 2017 г. 3:27 PM пользователь "Sebastian Wilzbach" <
notifications@github.com> написал:

So when I add the following to requests.d:

template exec(string method="GET") {
    Response exec(A...)(A args) {
        return _http.exec!(method)(args);
    }
}alias put = exec!"PUT";

then I get this weird error from Tuple.opAssign:

requests 0.4.0+commit.4.g520d041: building configuration
"__test__std__".../usr/include/dlang/dmd/std/typecons.d(740,39):
Error: template std.algorithm.mutation.swap cannot deduce function
from argument types !(Tuple!(_Response delegate(const(App), ref
HTTPD_Request, RequestArgs), RequestArgs))(Tuple!(_Response
delegate(const(App), ref HTTPD_Request, RequestArgs), "handler",
RequestArgs, "args"), Tuple!(_Response delegate(const(App), ref
HTTPD_Request, RequestArgs), "handler", RequestArgs, "args")),
candidates are:/usr/include/dlang/dmd/std/algorithm/mutation.d(2359,6):
       std.algorithm.mutation.swap(T)(ref T lhs, ref T rhs) if
(isBlitAssignable!T &&
!is(typeof(lhs.proxySwap(rhs))))/usr/include/dlang/dmd/std/algorithm/mutation.d(2575,6):
       std.algorithm.mutation.swap(T)(ref T lhs, ref T rhs) if
(is(typeof(lhs.proxySwap(rhs))))

So it seems that a trivial alias doesn't work that well.
Interestingly it compiles fine with ldc 1.0.0 (2.070). So this could be a
regression.

I'd also like to make some cleanup in API - it seems that some interfaces
overlaps - for example there are several ways to use query parameters
(using string dictionary and using QueryParams). May be this will be my
next goal, but I'm afraid to break others code.

As long as you provide a nice changelog and use semantic versioning
<http://semver.org/> you shouldn't worry too much about breaking code.
Thanks to DUB and semantic versioning you won't break existing code. Only
motivated users who want to play with the newest and hottest will be
affected ;-)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ikod/dlang-requests/issues/34#issuecomment-277803155>,
or mute the thread

**Comment by ikod** [comment]
Looks like done.
Thanks for report!
