### ISSUE TITLE
Build fails using dmd 2.072.0

### ISSUE THREAD

**Issue by pheerai** [ikod/dlang-requests#30]
dlang-requests fails to build using dmd/libphobos 2.072.0 and dub 1.0.0 on Arch Linux, x86_64.

I tried a clean build from the git sources as well as a build from a project depending on requests.

The error message is:
```d
source/requests/server/httpd.d(714,9): Error: pure constructor 'requests.server.httpd.RequestArgs.this' cannot call impure destructor 'std.regex.Captures!(string, ulong).Captures.~this'
```

**Comment by ikod** [comment]
Hello,
Will check today

6 Ноя 2016 г. 15:41 пользователь "Oliver Rümpelein" <
notifications@github.com> написал:

**Comment by ikod** [comment]
Hello @pheerai 

I commited fix, can you please test it?

**Comment by pheerai** [comment]
Building works for me now.

**Comment by ikod** [comment]
thanks, I will close issue.
